### ISSUE TITLE
Pip Documentation

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#25]
![image](https://user-images.githubusercontent.com/52835045/137070285-5a46d73d-d3e9-40fc-ab0e-f3ecdddd77b2.png)

<h1>We can remove Install Dependencies part in pip documentation</h1>

**Comment by Lakshmikanth2001** [comment]
Changes or not reflected on https://pypi.org/project/electricpy/#description

**Comment by Lakshmikanth2001** [comment]
We can we expect next release of electricpy pip packages so that we can act up on feedback and improve our package

**Comment by engineerjoe440** [comment]
@Lakshmikanth2001, I'm glad you stuck with this one... I'm sorry it took me so long, but I wanted to build the infrastructure that would allow the automated deployment of the source code directly from a GitHub action (which it now does!!!) so that future updates would be much simpler. I'm proud to announce that I've updated the released version on PyPI. Thank you again!
