### ISSUE TITLE
Issues with release.yml github actions

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#34]
Traceback (most recent call last):
  File "/home/runner/work/ElectricPy/ElectricPy/release-version.py", line 29, in <module>
    raise ValueError(
ValueError: Module version (v0.2.1) is not newer than previous release (v0.2.1)!

Every time when I pushed my local changes to GitHub release.yml is giving this error

**Comment by engineerjoe440** [comment]
Hi @Lakshmikanth2001! Yes... That's due to the fact that the automated release script is trying to validate that what's in the source code is new content. Since you're not *actively* releasing the source code, it fails the check and aborts the script. This is to be expected. I'd like to set up the workflow so that it doesn't run in repository forks, but I haven't found an effective way to do that, yet.

In the interim, you can disable the workflow(s) in your fork:
![Screenshot_20211210_204632](https://user-images.githubusercontent.com/33275230/145664242-77f1f67d-d504-4624-9c69-183fdf21a671.png)
