### ISSUE TITLE
Kudos & Structure Suggestion

### ISSUE THREAD

**Issue by danieldjewell** [engineerjoe440/ElectricPy#4]
First off, kudos, this project is way cool - I'm not sure there is even anything quite like this out there for Python...

Just a few random unsolicited thoughts:
- Consider grouping calculations into a module/file/class that are related (e.g. AC-related vs DC-related); That way, you could reuse function names if needed
- Consider using less abbreviations (I know this one is tough): 
  - Think about packages like pandas or even matplotlib - the names are rarely abbreviated - it might be long, but it's much easier to use without having to read through lots of documentation. The [metpy.calc](https://github.com/Unidata/MetPy/tree/master/src/metpy/calc) module is a really good example of this, I think. 
  - This applies to function parameters too - Someone who is an EE probably knows the abbreviations for inputs to formulae by heart, but someone who doesn't will definitely have to read the docs. **But a big kudos on the docs - they're very descriptive and complete!**
- The use case of metpy is obviously different (and it's designed for tight integration with xarray for manipulating meteorological data), but one thing that's really nice is the integration with ```pint``` for units. (See https://github.com/Unidata/MetPy/blob/master/src/metpy/units.py) It works with numpy arrays too - so you can pass numpy-unit aware arrays into calculation functions and it just handles it. 
  - Luckily, EE doesn't have too much unit befuddlement (unlike meteorology or other physical sciences where you have a mishmash of feet/meters/inches/etc.) - Amps are Amps, etc. But Pint does have some nice features like being able to add/deal with metric prefixes (e.g. it already has support for Volts, Amps, Henries, Ohms, Farads, etc. and it will handle prefix conversion automatically:
```python
import pint
u = pint.UnitRegistry()

cap1=20*u.nF
cap2=0.67*u.uF
ctotal=cap1+cap2 
ctotal
>690 <Unit('nanofarad')>
ctotal.to(u.uF)
>0.690000[...] <Unit('microfarad')>
```

Example of a function: https://github.com/engineerjoe440/ElectricPy/blob/6cf0bed70e310d5cfb9474e835dae969d1972cb8/electricpy/fault.py#L1520

Just some thoughts :)

**Comment by engineerjoe440** [comment]
Hey, @danieldjewell! Thanks for the kind words, and suggestions! They are very much appreciated!

I really like the idea of grouping into more discrete modules within the package. I hadn't considered the AC/DC division (but really like that idea) I will have to mull it over and see if I can think of a good break for it. I've toyed around with breaking out things like all of the capacitor functions (since there's a lot of them) and some of the motor ones too, so perhaps I'll make a breaking change for that with a big version bump.

I agree, the abbreviations are a bit annoying... I've definitely gone back and forth on this more than once while developing. In earnest, this is probably my fourth or fifth "structure" for the whole package, and the same goes for a lot of the names. I'll definitely consider that going forward, and try to make function names (and arguments) less of an abbreviation nightmare. Again, really appreciate the honest feedback!

Units are always a bit of a pain. I had considered utilizing `pint` early on in the development of the package, and ultimately decided against it since I suspected that it would add a fair bit of challenge to the whole thing. I suppose many (if not all) functions could simply accept arguments that would be tested against pint objects, but I didn't want to add that complexity early on. Especially since I had hoped to keep the functions focused on functionality, and "light" in the "units arena". Though this is still a valid point. Perhaps much of this hesitation is simply an artifact of my poor experiences with MathCAD tooling and unit support during my early undergrad years. Though useful in many simple cases, it often backed me into tricky corners when I least expected it.

Again, thank you SO much!!!! Sometimes I feel that any feedback can be a bit scarce, so your input is greatly appreciated! If you should run into anything specifically that gives you grief, or would like to see changed; feel free to let me know, or open a PR!

I'm going to leave this issue open so that if others wish to chime in, they may.

**Comment by engineerjoe440** [comment]
Heh... I guess I should also say THANK YOU for the comments about the docs. I spent a LOT of time working out countless kinks, and I think there's still a fare share. I fell in love with thorough documentation, and I felt that engineers who may aim to use this (or other packages) would appreciate seeing the core formulas that functions are using. That was SUPER important to me.

Thanks again!
