### ISSUE TITLE
`Bug` in `sphinx-build.yml`

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#78]
```
  remote: Permission to Lakshmikanth2001/ElectricPy.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/Lakshmikanth2001/ElectricPy.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
sphinx-build is failling in my forked repository

**Comment by engineerjoe440** [comment]
Hmm... Unfortunately I'm not familiar with a solid solution to this, but it would be ideal to figure this out so we can "check" the sphinx stuff in forked repos for validation.

**Comment by Lakshmikanth2001** [comment]
any updates sir

**Comment by engineerjoe440** [comment]
I'm afraid I don't have any updates. This appears to be an issue realted to users who've forked the primary ElectricPy repository (such as yourself). It's not something that I've been able to reproduce, and I think that for me to be able to attempt reproducing it, I'd need to set up a second GitHub account just for testing. Entirely possible, just not something that I've done yet, since it's a bit of a chore to investigate at this point.

I think that this isn't a key, blocking issue for development. Certainly an inconvenience, if not an frustration, but I don't think it will be a real stopping point.

If you have any thoughts on what we might experiment with to resolve the issue, I'd be very happy to hear them!

**Comment by Lakshmikanth2001** [comment]
No this issue is resolved my bad
