### ISSUE TITLE
`ElectricPy` website bug

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#94]
**Describe the bug**

**Reproduction Code**
`docsource/index.rst`
```python
# Setup
-------------------------
Contents:
-------------------------

.. toctree::
   :maxdepth: 1
   
   electricpyapi
   constants
   additionalresources
   changes
   Github <https://github.com/engineerjoe440/ElectricPy>
   PyPI <https://pypi.org/project/electricpy>


# Code which causes failure
   Github <https://github.com/engineerjoe440/ElectricPy>
   PyPI <https://pypi.org/project/electricpy>
```

**Expected behavior**
## proper logo rendering
![image](https://user-images.githubusercontent.com/52835045/175567450-c47dc2fe-287d-4ce5-b976-c8b176c76069.png)

**Screenshots**
## Acutal web site
![image](https://user-images.githubusercontent.com/52835045/175566083-14bb142b-604a-4180-991e-a1f8f13bf728.png)

**Additional context**
[ElectricPy](https://engineerjoe440.github.io/ElectricPy/) { URL from google top search )

**Comment by engineerjoe440** [comment]
Looks like this might be something related to the transition to use ReadTheDocs: https://electricpy.readthedocs.io/en/latest/

That said, there's still some issues there:
![image](https://user-images.githubusercontent.com/33275230/176974838-e1c23aa1-5130-4908-a610-35b4002e06f8.png)

**Comment by engineerjoe440** [comment]
OK! I think I've corrected this with the use of the `MyST-Parser` package (rather than `m2r2`, which seems to have been the culprit). I'll note that the change is only relevant on the GH-pages site, and the [`develop` branch of the ReadTheDocs site](https://electricpy.readthedocs.io/en/develop/) as of this moment in time. It'll update the `latest` branch when we cut a new release of `ElectricPy` (which I'll need to start thinking about, here, pretty soon).

![image](https://user-images.githubusercontent.com/33275230/176977984-a321c084-8beb-47e2-9b52-4c142a2e84c9.png)

![image](https://user-images.githubusercontent.com/33275230/176977988-ea313885-dd44-44b0-b349-3d6571aed43a.png)
